name: Compilar FilzaSlop dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Instalar dependencias
        run: |
          brew install ldid dpkg make
          echo "/opt/homebrew/opt/make/libexec/gnubin" >> $GITHUB_PATH
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Compilar
        run: |
          export SYSROOT=$(xcrun --sdk iphoneos --show-sdk-path)
          export TARGET=iphone:clang:latest:18.0
          make clean
          make package FINALPACKAGE=1

      - name: Subir dylib
        uses: actions/upload-artifact@v4
        with:
          name: filzaslop-dylib
          path: |
            .theos/obj/*.dylib
            packages/*.deb
